### ISSUE TITLE
Complete Parse Server

### ISSUE THREAD

**Issue by carnivash** [phillwiggins/FlutterParseSDK#2]
Hello, are all Parse Server features (Livequery, Local datastore, Query cache, cloud functions, etc..) implemented?

**Comment by phillwiggins** [comment]
Hey

Not yet. It's a work in progress.

There's a lot to do in terms of queries. The project currently connects to
a Parse Server, can get and save objects and login. It's an updated version
of an old attempt I found. I'm currently working on this along side a
Flutter project I have but there's a few issues I'm hitting.

**Comment by carnivash** [comment]
Thank you.
